### ISSUE TITLE
you can do like first create login screen in dart and then navigate it into webview

### ISSUE THREAD

**Issue by Abhishek01039** [gauravmehta13/ShalaDarpan_Webview#1]

**Comment by Abhishek01039** [comment]
@gauravmehta13

**Comment by gauravmehta13** [comment]
> @gauravmehta13

Will the login screen automatically login us to fb and then show profile?

**Comment by Abhishek01039** [comment]
you can not do anything inside the webivew 
so you have to follow the procedure of how to login in Facebook.

**Comment by Abhishek01039** [comment]
which profile?
you mean profile page then yes why not 
if you are using firebase then you can use firebaseUser otherwise you have to store the data in local machine

**Comment by gauravmehta13** [comment]
ok thanks
